# -*- coding: utf-8 -*-
"""Assignment_3_23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gdeoWc_5t5v_5hmVFR_MULkaSZ03MoWa

1.	Write a Python program to find area of a circle using math module.
"""

import math
r=int(input("entre the radius of circle : "))
A=math.pi*r*r
print("The area of the circle is ",A)

"""2.	Write a program to find Area of Regular Polygon."""

import math
s=int(input("enter the number of sides : "))
l=int(input("enter the length of a sides : "))
A=s*(l**2)/(4*math.tan(math.pi/s))
print("The area of polygon is ",A)

"""3.	Write a program to find Area of a Segment of a Circle Formula using math module."""

import math
r=float(input("enter the radius: "))
a=float(input("enter the angle: "))
area=(math.pi*r**2)*(a/360)
print("The area of segment of circle is: ",area)

"""4.	Write a python program to generate random number from list l1=[100,1,2,3,30,40]."""

import random
print("The random number from list l1 is ",random.choice([100,1,2,3,30,40]))

"""5.	Write a program to generate random numbers between 1,10000 and difference between each random number is 50."""

import random
print("The random number from range is ",random.randrange(1,10000,50))

"""6.	Write a python program by using math module to find"""

import math
print("The angle is sin60 is: ",math.sin(60))
print("The value of cospi is: ",math.cos(math.pi))
print("The value of tan90 is: ",math.tan(90))
print("The angle of sin is: ",math.asin(0.8660254037844386))
print("The use of xor bitwise operator is: ",5^8)
print("The square root of 400 is: ",math.sqrt(400))

print("The value of log(1024) is: ",math.log2(1024))
print("The value of Log(1024), base 10 is: ",math.log10(1024))
print("The Floor and Ceiling value of 23.56 is: ",math.floor(23.56),math.ceil(23.56))

