# -*- coding: utf-8 -*-
"""Assignment_2_20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O7oDTaOvmTYPrsaYZIszdMxAhgUtKltb

1. Write a program in python to check whether a person is eligible for voting or not using if-else.
"""

age=int(input("enter the age of the person"))
if age>=18:
  print("The person is eligible to vote")
else:
  print("The person is not eligible to vote")
print("This is ELECTION RULE")

"""2. Write a program to check whether a number is even or odd using if-else."""

num=int(input("enter the number"))
if num%2==0:
  print(num,"The number is even")
else:
  print(num,"The number is odd")

"""3. Write a program to print the string in reverse order by using string indexing"""

s1=(input("enter the string"))
reverse=s1[::-1]
print("The reverse of given string is",reverse)

"""4. Write a python program to check whether a number is positive or not using if-else."""

num=int(input("enter the number"))
if num>0:
  print("The number is positive",num)
else:
  print("The number is negative",num)

"""5. Write a python program to find the roots of a quadratic equation using elif."""

import math
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
c=int(input("enter the value of c"))
d=((b*b)-4*a*c)
if d>0:
  r1=(-b + math.sqrt(d))/(2*a)
  r2=(-b - math.sqrt(d))/(2*a)
  print("root1",r1,"root2",r2)
elif d==0:
  r1=r2=-b/(2*a)
  print("root1 is equal to root2",r1)
else:
  rp=-b/(2*a)
  ip= math.sqrt(-d)/(2*a)
  print("real part",rp,"imaginary part",ip)

"""6. Write  a program using nested-if to check whether a number is positive or negative or zero."""

num=int(input("enter the number"))
if num<=0:
  if num>=0:
    print("The number is zero")
  else:
    print("the number is negative")
else:
  print("the number is positive")

"""7. Write a program to accept a number(1-5) and print the given number in words."""

num=int(input("enter the number"))
if num==1:
  print("The number is said to be ONE")
elif num==2:
  print("The number is said to be TWO")
elif num==3:
  print("The number is said to be THREE")
elif num==4:
  print("The number is said to be FOUR")
elif num==5:
  print("The number is said to be FIVE")
else:
  print("The number is invalid")

"""8. Write a program to read a character and print the given character is vowel or consonant."""

ch = input("Enter a character: ")
if(ch=='A' or ch=='a' or ch=='E' or ch =='e' or ch=='I'
 or ch=='i' or ch=='O' or ch=='o' or ch=='U' or ch=='u'):
    print(ch, "is a Vowel")
else:
    print(ch, "is a Consonant")

