# -*- coding: utf-8 -*-
"""Assignment_1_18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/hemanth0115/Demo/blob/master/Assignment_1_18.ipynb

1.	Write a python program to design simple calculator for the operators
"""

s=int(input("enter the number a"))
h=int(input("enter the number b"))
print("The addition is",s+h)
print("the subraction is",s-h)
print("the multipication is",s*h)
print("the division is",s/h)
print("the floor division is",s//h)
print("the modulus division is",s%h)
print("the exponential is",s**h)

"""2.	Write a python program to calculate simple interest."""

p=float(input("enter the value of p"))
t=float(input("enter the value of t"))
r=float(input("enter the value of r"))
si=p*t*r/100
print("the simple intrest is",si)

"""3.	Write a python program to calculate area of a circle."""

r=int(input("enter the value of r"))
A=3.14*r*r
print("Area of circle is",A)

"""4.	Write a python program to calculate area of a triangle."""

b=float(input("enther the value of b"))
h=float(input("enter the value of h"))
A=1/2*b*h
print("Area of a triangle",A)

"""5.	Write a python program to temperature in Celsius to Fahrenheit"""

c=float(input("enter the value of celsius"))
F=(c*1.8)+32
print("the temperature of fahrenheit",F)

"""6.	Write a python program to calculate area of rectangle"""

l=int(input("enter the value of length"))
w=int(input("enter the value of width"))
A=l*w 
print("area of rectangle",A)

"""7.	Write a python program to calculate perimeter of a square"""

a=int(input("enter the value of a"))
P=4*a
print("Perimeter of a square",P)

"""8.	Write a python program to calculate circumference of a circle."""

r=int(input("enter the value of radius"))
C=2*3.14*r
print("Circumferenceof a circle",C)

"""1.	Write a python program to swap two numbers."""

a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
a=a+b
b=a-b
a=a-b
print("the swaping of two number",a,b)

